# docker-compose-prod.yml
version: "3"
services:
  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        SERVER_IMAGE_TAG: ${SERVER_IMAGE_TAG}
    image: e-mission/opdash:0.0.1
    ports:
      - "8050:8050"
    environment:
      DASH_DEBUG_MODE: "False"
      DASH_SERVER_PORT: 8050
      DB_HOST: db
      WEB_SERVER_HOST: 0.0.0.0
      SERVER_BRANCH: master
      STUDY_CONFIG: "stage-program"
      CONFIG_REPO: "e-mission/nrel-openpath-deploy-configs"
      CONFIG_UDPATES_WORKFLOW: "config-update.yml"
      CONFIG_UPDATES_GH_APP_PRIVATE_KEY: ""
      CONFIG_UPDATES_GH_APP_ID: ""
      CONFIG_UPDATES_GH_APP_INSTALLATION_ID: ""
      AUTH_TYPE: "basic" # the other option is cognito
      COGNITO_CLIENT_ID: ''
      COGNITO_CLIENT_SECRET: ''
      COGNITO_REDIRECT_URL: ''
      COGNITO_TOKEN_ENDPOINT: ''
      COGNITO_USER_POOL_ID: ''
      COGNITO_REGION: ''
      COGNITO_AUTH_URL: ''
      REACT_VERSION: "18.2.0"
    networks:
       - emission
    deploy:
      restart_policy:
          condition: on-failure
    depends_on:
      - db
  db:
    image: mongo:8.0.4
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mongo-data:/data/db
    networks:
       - emission

networks:
  emission:

volumes:
  mongo-data:
